### ISSUE TITLE
Getting "cannot call method 'indexOf'" when running node app.js

### ISSUE THREAD

**Issue by davpx** [gondek/pagerduty-dashboard#1]
Any suggestions?

TypeError: Cannot call method 'indexOf' of undefined
    at isPrimaryService (/Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:148:30)
    at getServiceName (/Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:165:7)
    at buildService (/Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:31:17)
    at /Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:21:33
    at Array.forEach (native)
    at buildServices (/Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:20:15)
    at module.exports (/Users/dolivas/Projects/pagerduty-dashboard/server/groups.js:11:22)
    at makeUpdatePackage (/Users/dolivas/Projects/pagerduty-dashboard/server/main.js:56:16)
    at /Users/dolivas/Projects/pagerduty-dashboard/server/main.js:40:24
    at /Users/dolivas/Projects/pagerduty-dashboard/server/main.js:51:5

**Comment by gondek** [comment]
Hi David,

Thanks for your interest. Does `node app.js` run when using mock data? (Use `mock: true` in `config.json`)

**Comment by davpx** [comment]
it does work with mock data, just not with my api key and subdomain set it seems

**Comment by gondek** [comment]
Could you replace `groups.js:148` with:

```
try {
    return service.description.indexOf('[dashboard-primary]') !== -1;
  } catch (e) {
    console.log(service);
    return false;
  }
```

and tell me what gets printed out?

**Comment by davpx** [comment]
I receive a list of all my pagerduty services and then a line with the date. Nothing afterwards and the web server doesn't start.

......
{"id":"REDACTED","name":"Test","service_url":"/services/REDACTED","service_key":"redacted@redacted.pagerduty.com","auto_resolve_timeout":14400,"acknowledgement_timeout":1800,"created_at":"2013-09-19T08:03:37-07:00","deleted_at":null,"status":"active","last_incident_timestamp":null,"email_incident_creation":"on_new_email_subject","incident_counts":{"triggered":0,"resolved":0,"acknowledged":0,"total":0},"email_filter_mode":"all-email","type":"generic_email","incident_urgency_rule":{"type":"constant","urgency":"high"},"scheduled_actions":[],"support_hours":null}
Sat Aug 08 2015 19:33:36 GMT-0700 (MST): Sending update.

**Comment by gondek** [comment]
Thanks David.

The issue here is that the object should have a `description` key as documented here: https://developer.pagerduty.com/documentation/rest/services/list

The missing description is the "undefined" in "TypeError: Cannot call method 'indexOf' of undefined".

I just set up a dashboard from scratch and it is working. On my end, I have services without descriptions that come back with the field as an empty string. I also went with a direct curl request and the services also show up with an empty description string.

As a sanity check, could you post the response from the below request for your subdomain and token?

```
curl -H "Content-type: application/json" -H "Authorization: Token token=TOKEN" -X GET -G "https://SUBDOMAIN.pagerduty.com/api/v1/services"
```

Some things I am considering:
- Maybe no descriptions on any service causes the API not to reply with any descriptions?
- The `buildService` function is messing up the object (during json parsing or object extension), which could be influenced by the environment?

What version of Node are you running?

**Comment by davpx** [comment]
Node version is v0.10.31, 

Description is empty on all services it seems. I don't see anywhere in my pagerduty account where I can populate this field.

Here's a sample of one

{"id":"REDACTED","name":"REDACTED","service_url":"/services/REDACTED","service_key":"REDACTED","auto_resolve_timeout":14400,"acknowledgement_timeout":1800,"created_at":"2014-09-05T08:40:53-07:00","deleted_at":null,"status":"active","last_incident_timestamp":null,"email_incident_creation":"on_new_email_subject","incident_counts":{"triggered":0,"resolved":0,"acknowledged":0,"total":0},"email_filter_mode":"all-email","type":"generic_email","incident_urgency_rule":{"type":"constant","urgency":"high"},"scheduled_actions":[],"support_hours":null,"description":""}

Is there a way to replace null values with an empty string or a space even though it doesn't seem like the best fix?

**Comment by gondek** [comment]
>Is there a way to replace null values with an empty string or a space even though it doesn't seem like the best fix?

I will go ahead and do that. If the API cannot guarantee the presence of that field (which it is not doing although the documentation suggests that it should), then my code should not assume that it exists.

> I don't see anywhere in my pagerduty account where I can populate this field.

When you're on the edit page for a service, to the right of the large field for the name, there's a light grey chevron titled "Description (optional)". You can find it with a CTRL-F. To prevent future confusion, would you mind adding a description and seeing if it changes the API response?

If it does end up changing things, I will add a note to the README. Either way, I will put in a code fix.

Thanks for your help diagnosing this issue.

**Comment by gondek** [comment]
Let me know if it works in the new version.
